baseURL = "https://ss-exhibition-1329853996.cos-website.ap-guangzhou.myqcloud.com"
DefaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false
languageCode = "zh"
title = "展览"
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6
summaryLength  = "30"

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "2006年1月2日"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = true
previewCardImagePlacement = "bottom"


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

[[menu.main]]
    name = "Collections"
    url = "/collections/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

