name: Build and Deploy Hugo to Tencent COS

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo \
            --minify

  # Deployment job
  deploy:
    environment:
      name: Tencent COS
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 4: Install Tencent COS CLI tool
      - name: Install COSCLI
        run: |
          wget https://cosbrowser.cloud.tencent.com/software/coscli/coscli-v1.0.1-linux-amd64 -O coscli
          if file coscli | grep -q "ELF"; then
            chmod +x coscli
            sudo mv coscli /usr/local/bin/coscli
            coscli --version
          else
            echo "Download failed or wrong file" >&2
            exit 1
          fi

      # Step 5: 上传到腾讯云 COS
      - name: Deploy to Tencent COS
        env:
          COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
          COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
          COS_BUCKET: ${{ secrets.COS_BUCKET }}
          COS_REGION: ${{ secrets.COS_REGION }}
        run: |
          coscli config add -a $COS_SECRET_ID -s $COS_SECRET_KEY -b $COS_BUCKET -r $COS_REGION
          coscli sync ./public/ cos://$COS_BUCKET/ --delete
